---
-
  gather_facts: false
  hosts: win
  tasks:
    -
      name: Ntp Config
      win_command: "{{ item }}"
      loop:
        - w32tm /query /peers
        - tzutil /g
        - win_command: w32tm /stripchart /computer:localhost /samples:0
